### PR TITLE
Output: retry other modes if preferred fails

### LINKED ISSUE #502: Only one external monitor activated when docking
I have a ThinkPad and when I dock it only one of two external monitors get activated. I confirmed that with sway it is working. 

I created a debug log: https://pastebin.com/ANG1QzDD

Notes:
- eDP-1 is internal, DP-3 and DP-4 are external
- on 11:33:33 the PC goes to sleep and wakes up at 11:34:11 (so you can search for it)
- there are several hotplug events (6) received and handled and in each of them the activation for DP-4 fails with the following
```
Jan 05 11:34:11 pc-klosi river[24421]: debug(output_manager): new output DP-4
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [backend/drm/drm.c:492] connector DP-4: Can't enable an output without a buffer
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [types/output/render.c:192] Attaching empty buffer to output for modeset
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [types/output/render.c:73] Choosing primary buffer format 0x34325258 for output 'DP-4'
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [render/swapchain.c:105] Allocating new swapchain buffer
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [render/allocator/gbm.c:140] Allocated 1920x1080 GBM buffer (format 0x34325258, modifier 0x100000000000002)
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [render/gles2/renderer.c:142] Created GL FBO for buffer 1920x1080
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [backend/drm/atomic.c:34] connector DP-4: Atomic test failed (modeset): Invalid argument
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [types/output/render.c:210] Output modeset test failed, retrying without modifiers
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [types/output/render.c:73] Choosing primary buffer format 0x34325258 for output 'DP-4'
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [render/swapchain.c:105] Allocating new swapchain buffer
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [render/allocator/gbm.c:140] Allocated 1920x1080 GBM buffer (format 0x34325258, modifier 0xFFFFFFFFFFFFFF)
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [render/gles2/renderer.c:142] Created GL FBO for buffer 1920x1080
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [backend/drm/atomic.c:34] connector DP-4: Atomic test failed (modeset): Invalid argument
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [backend/drm/drm.c:1017] connector DP-4: De-allocating CRTC 2
Jan 05 11:34:11 pc-klosi river[24421]: debug(wlroots): [backend/session/session.c:182] udev event for card0-DP-4 (add)
```

### PR DESCRIPTION
**Pull request by tiosgz**
In cases like multiple hi-res monitors connected through a USB dock, the
preferred mode can fail to work. Such an output was then ignored by river,
which made it impossible to even set another mode manually.

Sway has been reported to solve this issue, so let's employ their solution
and fall back to another mode if possible.

Likely fixes #502.

### CODE REVIEW

File: river/Output.zig [hunk 1]
```diff
@@ -105,10 +105,18 @@ pub fn init(self: *Self, wlr_output: *wlr.Output) !void {
...
-        try wlr_output.commit();
+        wlr_output.commit() catch |err| if (!wlr_output.modes.empty()) {
+            var it = wlr_output.modes.iterator(.forward);
+            while (it.next()) |mode| {
+                if (mode == preferred_mode) continue;
+                wlr_output.setMode(mode);
+                wlr_output.commit() catch continue;
+                break;
+            } else return err;
+        } else return err;
```
Comment (ifreund) [inline river/Output.zig:119]: Is this if really necessary? I think this could be simplified to the following
```suggestion
    wlr_output.commit() catch |err| {
        var it = wlr_output.modes.iterator(.forward);
        while (it.next()) |mode| {
            if (mode == preferred_mode) continue;
            wlr_output.setMode(mode);
            wlr_output.commit() catch continue;
            break;
        } else {
            return err;
        }
    };
```

**Review by ifreund — COMMENTED** [review]
Thanks for taking a look at this! I'll give it a bit of time for users that were able to reproduce the issue on their hardware to test this patch but I don't see any reason not to merge this.

File: river/Output.zig (hunk 1 above)
Comment (tiosgz) [reply river/Output.zig:119]: Ah, right. Blindly copied from sway 🤦

**Comment by tiosgz** [comment]
Can i do something about the CI?

**Comment by ifreund** [comment]
> Can i do something about the CI?

Not sure what's going on there but it's clearly not a result of your changes here. I'll take a look in a bit.

**Review by ifreund — APPROVED** [review]
LGTM, Thanks!

CI should be fixed by 403eca90a5956a62259dc252ca0dbcd332790580
